CREATE TABLE watchlist_source_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(100) NOT NULL,
    requested_version VARCHAR(80) NOT NULL,
    payload_format VARCHAR(10) NOT NULL,
    trigger_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    payload_checksum VARCHAR(64),
    correlation_id VARCHAR(64) NOT NULL,
    actor_username VARCHAR(120),
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    safe_error_code VARCHAR(80),
    total_rows INTEGER NOT NULL DEFAULT 0,
    added_count INTEGER NOT NULL DEFAULT 0,
    changed_count INTEGER NOT NULL DEFAULT 0,
    removed_count INTEGER NOT NULL DEFAULT 0,
    unchanged_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT ck_watchlist_source_runs_status CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED'))
);
CREATE INDEX idx_watchlist_source_runs_started_at ON watchlist_source_runs(started_at DESC);
CREATE INDEX idx_watchlist_source_runs_provider ON watchlist_source_runs(provider, requested_version);

CREATE TABLE watchlist_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(100) NOT NULL,
    source_version VARCHAR(80) NOT NULL,
    payload_checksum VARCHAR(64) NOT NULL,
    source_run_id BIGINT NOT NULL UNIQUE REFERENCES watchlist_source_runs(id),
    collected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    total_rows INTEGER NOT NULL,
    added_count INTEGER NOT NULL,
    changed_count INTEGER NOT NULL,
    removed_count INTEGER NOT NULL,
    unchanged_count INTEGER NOT NULL,
    CONSTRAINT uq_watchlist_snapshot_payload UNIQUE (provider, source_version, payload_checksum)
);
CREATE INDEX idx_watchlist_snapshots_provider_collected ON watchlist_snapshots(provider, collected_at DESC);

CREATE TABLE watchlist_snapshot_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id BIGINT NOT NULL REFERENCES watchlist_snapshots(id),
    external_id VARCHAR(160) NOT NULL,
    entity_name VARCHAR(255) NOT NULL,
    aliases TEXT NOT NULL,
    country_code VARCHAR(2),
    listing_reason VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    data_origin VARCHAR(20) NOT NULL,
    canonical_hash VARCHAR(64) NOT NULL,
    CONSTRAINT uq_watchlist_snapshot_external_id UNIQUE (snapshot_id, external_id)
);
CREATE INDEX idx_watchlist_snapshot_records_lookup ON watchlist_snapshot_records(snapshot_id, entity_name, country_code);

CREATE TABLE watchlist_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_run_id BIGINT NOT NULL REFERENCES watchlist_source_runs(id),
    snapshot_id BIGINT NOT NULL REFERENCES watchlist_snapshots(id),
    previous_snapshot_id BIGINT REFERENCES watchlist_snapshots(id),
    change_type VARCHAR(20) NOT NULL,
    external_id VARCHAR(160) NOT NULL,
    entity_name VARCHAR(255) NOT NULL,
    differences_json TEXT NOT NULL,
    CONSTRAINT ck_watchlist_changes_type CHECK (change_type IN ('ADDED', 'CHANGED', 'REMOVED')),
    CONSTRAINT uq_watchlist_change_per_run UNIQUE (source_run_id, external_id, change_type)
);
CREATE INDEX idx_watchlist_changes_snapshot_type ON watchlist_changes(snapshot_id, change_type);