CREATE TABLE import_runs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 file_name VARCHAR(255) NOT NULL, file_checksum VARCHAR(64) NOT NULL,
 status VARCHAR(30) NOT NULL, correlation_id VARCHAR(64) NOT NULL, actor_username VARCHAR(120),
 started_at TIMESTAMP WITH TIME ZONE NOT NULL, completed_at TIMESTAMP WITH TIME ZONE,
 accepted_count INTEGER NOT NULL DEFAULT 0, rejected_count INTEGER NOT NULL DEFAULT 0, duplicate_count INTEGER NOT NULL DEFAULT 0,
 CONSTRAINT ck_import_runs_status CHECK (status IN ('RUNNING','COMPLETED','COMPLETED_WITH_ERRORS','FAILED')),
 CONSTRAINT uq_import_runs_checksum UNIQUE (file_checksum)
);
CREATE TABLE trade_transactions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 import_run_id BIGINT NOT NULL REFERENCES import_runs(id), transaction_id VARCHAR(100) NOT NULL,
 transaction_date DATE NOT NULL, counterparty_name VARCHAR(255) NOT NULL, country_code VARCHAR(2),
 amount_usd NUMERIC(18,2) NOT NULL, currency VARCHAR(3) NOT NULL, data_origin VARCHAR(20) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT uq_trade_transactions_transaction_id UNIQUE (transaction_id),
 CONSTRAINT ck_trade_transactions_origin CHECK (data_origin = 'FICTIONAL')
);
CREATE INDEX idx_trade_transactions_month ON trade_transactions(transaction_date);
CREATE INDEX idx_trade_transactions_counterparty ON trade_transactions(counterparty_name);
CREATE TABLE import_row_rejections (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, import_run_id BIGINT NOT NULL REFERENCES import_runs(id),
 row_number INTEGER NOT NULL, error_code VARCHAR(80) NOT NULL, field_name VARCHAR(80), created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_import_rejections_run ON import_row_rejections(import_run_id,row_number);