CREATE TABLE screening_reviews (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, transaction_id VARCHAR(100) NOT NULL,
 watchlist_external_id VARCHAR(160) NOT NULL, match_score NUMERIC(5,4) NOT NULL, disposition VARCHAR(30) NOT NULL,
 actor_username VARCHAR(120) NOT NULL, correlation_id VARCHAR(64) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT ck_screening_score CHECK (match_score >= 0 AND match_score <= 1),
 CONSTRAINT ck_screening_disposition CHECK (disposition IN ('CONFIRMED_MATCH','CLEARED','NEEDS_FOLLOW_UP'))
);
CREATE INDEX idx_screening_reviews_transaction ON screening_reviews(transaction_id,created_at DESC);