CREATE TABLE bis_sources (
 code VARCHAR(8) PRIMARY KEY, current_snapshot_id BIGINT, active_run_id BIGINT,
 download_url TEXT, final_url TEXT, etag TEXT, last_modified TEXT,
 last_checked TIMESTAMP WITH TIME ZONE, last_success TIMESTAMP WITH TIME ZONE,
 next_scheduled TIMESTAMP WITH TIME ZONE, alert_code VARCHAR(80)
);
INSERT INTO bis_sources(code) VALUES('DPL'),('EL');
CREATE TABLE bis_runs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 source_code VARCHAR(8) NOT NULL REFERENCES bis_sources(code), trigger_type VARCHAR(20) NOT NULL,
 actor VARCHAR(120), correlation_id VARCHAR(64) NOT NULL,
 status VARCHAR(30) NOT NULL, stage VARCHAR(40) NOT NULL,
 started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at TIMESTAMP WITH TIME ZONE,
 guide_url TEXT, download_url TEXT, final_url TEXT, previous_url TEXT, page_hash VARCHAR(64),
 etag TEXT, last_modified TEXT, file_hash VARCHAR(64), file_path TEXT, file_size BIGINT,
 total_rows INTEGER NOT NULL DEFAULT 0, warnings INTEGER NOT NULL DEFAULT 0, rejected_rows INTEGER NOT NULL DEFAULT 0,
 added_rows INTEGER NOT NULL DEFAULT 0, removed_rows INTEGER NOT NULL DEFAULT 0, unchanged_rows INTEGER NOT NULL DEFAULT 0,
 snapshot_id BIGINT, error_code VARCHAR(80), idempotent BOOLEAN NOT NULL DEFAULT FALSE,
 parser_version VARCHAR(30) NOT NULL DEFAULT 'bis-csv-1', approved_by VARCHAR(120), approved_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_bis_runs_time ON bis_runs(id DESC);
CREATE TABLE bis_snapshots (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 source_code VARCHAR(8) NOT NULL REFERENCES bis_sources(code), run_id BIGINT NOT NULL REFERENCES bis_runs(id),
 file_hash VARCHAR(64) NOT NULL, total_rows INTEGER NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE bis_records (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 snapshot_id BIGINT NOT NULL REFERENCES bis_snapshots(id), run_id BIGINT NOT NULL REFERENCES bis_runs(id),
 source_code VARCHAR(8) NOT NULL, row_number INTEGER NOT NULL, occurrence INTEGER NOT NULL,
 raw_hash VARCHAR(64) NOT NULL, raw_json TEXT NOT NULL, name TEXT NOT NULL,
 country TEXT NOT NULL, country_label TEXT NOT NULL, address TEXT NOT NULL,
 aliases_json TEXT NOT NULL, dates_json TEXT NOT NULL, validation VARCHAR(20) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(snapshot_id,row_number)
);
CREATE INDEX idx_bis_records_snapshot ON bis_records(snapshot_id,raw_hash);
CREATE INDEX idx_bis_records_filters ON bis_records(source_code,country,snapshot_id);
CREATE TABLE bis_search_names (
 record_id BIGINT NOT NULL REFERENCES bis_records(id) ON DELETE CASCADE,
 snapshot_id BIGINT NOT NULL, name TEXT NOT NULL, normalized TEXT NOT NULL, compact TEXT NOT NULL,
 tokenized TEXT NOT NULL, kind VARCHAR(20) NOT NULL
);
CREATE INDEX idx_bis_names_snapshot ON bis_search_names(snapshot_id);
CREATE INDEX idx_bis_names_normalized ON bis_search_names(normalized);
CREATE TABLE bis_row_issues (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, run_id BIGINT NOT NULL REFERENCES bis_runs(id),
 row_number INTEGER NOT NULL, code VARCHAR(80) NOT NULL, severity VARCHAR(10) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE search_history (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username VARCHAR(120) NOT NULL,
 query_json TEXT NOT NULL, total_results INTEGER NOT NULL, elapsed_ms BIGINT NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_search_history_owner ON search_history(username,id DESC);

